"""
derive.py — build the derived analysis table from the frozen corpus.

Input : data/SustFin_Corpus_FINAL.csv   (frozen, 109 rows, never edited by this script)
Output: data/sustfin_datasets.csv       (frozen fields + derived fields)
        data/sustfin_datasets.json      (same content, machine-readable)

Every derived field is defined here and nowhere else. If a scoring key or a
source classification changes, it changes in this file and the whole repository
is regenerated by rerunning `make build`.
"""

import csv
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "data", "SustFin_Corpus_FINAL.csv")

# ---------------------------------------------------------------------------
# Scoring keys (documented in docs/CODEBOOK.md §3)
# ---------------------------------------------------------------------------

DATA_SCORE = {
    "Y": 1.00,          # constructed panel released
    "Partial": 0.75,    # some but not all of the analysis data released
    "Raw Data": 0.50,   # public raw sources named; nothing released
    "On Demand": 0.25,  # available from the authors on request
    "N": 0.00,          # no public pathway
}

CODE_SCORE = {
    "Y": 1.00,
    "Partial": 0.50,
    "On Demand": 0.25,
    "N": 0.00,
}

# ---------------------------------------------------------------------------
# Source classification (documented in docs/CODEBOOK.md §4)
# A source is LICENSED if access requires a commercial subscription or a
# negotiated agreement; PUBLIC if it is retrievable by any researcher without
# payment or permission. Sources that are neither (author-generated survey and
# experimental data, residual "Other") fall through to NEITHER.
# ---------------------------------------------------------------------------

LICENSED = {
    "Proprietary Database",
    "Market Data",
    "Earnings Call transcripts",
    "News & Media",
}

PUBLIC = {
    "Official Statistics",
    "SEC Filings",
    "Weather & Hazard",
    "Satellite Imagery",
    "CDP Reports",
}

# ---------------------------------------------------------------------------
# Topic flags -> six consolidated clusters (documented in docs/CODEBOOK.md §5)
# Clusters are non-exclusive: a paper carrying several flags joins several
# clusters, so cluster counts sum above 109.
# ---------------------------------------------------------------------------

CLUSTERS = {
    "Biodiversity & Nature": ["Topic: Biodiversity & Nature"],
    "Climate Physical Risk": ["Topic: Climate Physical Risk"],
    "Climate Transition Risk & Corporate Emissions": [
        "Topic: Climate Transition Risk",
        "Topic: Corporate Emissions (Scope 1/2/3)",
    ],
    "Green Bonds & Sustainable Debt": ["Topic: Green Bonds & Sustainable Debt"],
    "Social & Governance": ["Topic: Social Factors", "Topic: Governance"],
    "ESG Disclosure & Ratings": ["Topic: ESG Disclosure", "Topic: ESG Ratings"],
}

TOPIC_FLAGS = [
    "Topic: Climate Physical Risk",
    "Topic: Climate Transition Risk",
    "Topic: ESG Disclosure",
    "Topic: ESG Ratings",
    "Topic: Biodiversity & Nature",
    "Topic: Green Bonds & Sustainable Debt",
    "Topic: Corporate Emissions (Scope 1/2/3)",
    "Topic: Social Factors",
    "Topic: Governance",
    "Topic: Other",
]

# Short codes used in the repository table, so a row stays readable.
TOPIC_CODE = {
    "Topic: Climate Physical Risk": "PHY",
    "Topic: Climate Transition Risk": "TRN",
    "Topic: ESG Disclosure": "DIS",
    "Topic: ESG Ratings": "RAT",
    "Topic: Biodiversity & Nature": "BIO",
    "Topic: Green Bonds & Sustainable Debt": "GRB",
    "Topic: Corporate Emissions (Scope 1/2/3)": "EMI",
    "Topic: Social Factors": "SOC",
    "Topic: Governance": "GOV",
    "Topic: Other": "OTH",
}

METHOD_CODE = {
    "Standard Econometrics Accounting / Market Data": "ECON",
    "NLP / Textual Analysis": "NLP",
    "Satellite & Remote Sensing": "SAT",
    "Survey Instrument": "SURV",
    "Experiment": "EXP",
    "Regulatory Filing Parsing": "FILE",
    "Machine Learning (non-NLP)": "ML",
    "Meta-Analysis / Systematic Review": "META",
    "Other": "OTH",
}

# Short codes for the raw data sources, so an input can be shown in a table
# cell. The licensing classification above is what determines LIC/PUB/—.
SOURCE_CODE = {
    "Proprietary Database": "PROP",
    "Market Data": "MKT",
    "Official Statistics": "OFF",
    "SEC Filings": "SEC",
    "Weather & Hazard": "WX",
    "Satellite Imagery": "SATI",
    "Earnings Call transcripts": "CALL",
    "News & Media": "NEWS",
    "CDP Reports": "CDP",
    "Survey Data": "SURV",
    "Social Media": "SOCM",
    "Other": "OTH",
}

LICENSING_CODE = {
    "licensed only": "LIC",
    "licensed and public": "MIX",
    "public only": "PUB",
    "neither": "—",
}


# Coarse label for the openness score, kept distinct in name from
# `curation_tier` (§7 of the codebook), which is a different classification.
OPENNESS_BAND = [
    # (lower bound inclusive, label)
    (1.00, "fully open"),
    (0.75, "mostly open"),
    (0.50, "partly open"),
    (0.25, "minimally open"),
    (0.00, "closed"),
]

# ---------------------------------------------------------------------------
# Periodisation (documented in docs/CODEBOOK.md §6; used throughout Chapter 4
# and Chapter 5 of the thesis for every period-by-period breakdown). Declared
# once here as the canonical cut, and mirrored (not stored as a 37th derived
# field, to keep the schema at 36) in build_docs.py and verify.py, which
# compute it on the fly from publication_year.
# ---------------------------------------------------------------------------

PERIOD_BOUNDS = [
    (2011, 2015, "2011–2015"),
    (2016, 2020, "2016–2020"),
    (2021, 2023, "2021–2023"),
    (2024, 2026, "2024–2026"),
]
PERIOD_ORDER = [label for _, _, label in PERIOD_BOUNDS]


def period_of(year):
    if year is None:
        return None
    for lo, hi, label in PERIOD_BOUNDS:
        if lo <= year <= hi:
            return label
    return None


def _flag(v):
    return v.strip().upper().startswith("Y")


def _year(v, pick=min):
    """Parse a year cell.

    One cell in the frozen corpus (P61) records two separate cross-sections
    rather than a range, as "2014; 2017". Where several years are listed, the
    start takes the earliest and the end the latest, so the coverage window
    spans everything the study observes.
    """
    years = [int(y) for y in re.findall(r"(?:1[89]|20)\d{2}", v or "")]
    return pick(years) if years else None


def licensing_exposure(row):
    s = {row["Data Source (primary)"].strip(), row["Data Source (secondary)"].strip()}
    s.discard("")
    lic, pub = bool(s & LICENSED), bool(s & PUBLIC)
    if lic and pub:
        return "licensed and public"
    if lic:
        return "licensed only"
    if pub:
        return "public only"
    return "neither"


def openness_band(score, data_lvl, code_lvl):
    if data_lvl == "Y" and code_lvl == "Y":
        return "fully open"
    for lo, label in OPENNESS_BAND:
        if score >= lo:
            return label if label != "fully open" else "mostly open"
    return "closed"


def curation_tier(data_lvl, code_lvl):
    """Curation tiers as defined in the thesis §6.2.

    Seven tiers, ordered by what a reader can actually recover. They are
    mutually exclusive, evaluated in order, and together they cover all 109
    papers: every entry carries exactly one tier.

    Something is downloadable
      Tier 1  data = Y                and code = Y        fully open
      Tier 2  data = Partial          and code = Y        code, panel in part
      Tier 3  data in (Y, Partial)    and code  < Y       panel, no full code

    Nothing is downloadable, but the pipeline is documented
      Tier 4  data = Raw Data         and code = Y        code names the inputs
      Tier 5  data = N                and code = Y        code documents a
                                                          pipeline whose inputs
                                                          are licensed
      Tier 6  data in (Raw Data,      and code  < Y       provenance recorded,
              On Demand)                                  nothing released

    Nothing is recoverable
      Tier 7  data = N                and code  < Y       closed

    Tiers 4 and 5 are the analytically interesting pair. Neither releases an
    analysis panel, so neither can be rerun, but the released code records where
    the inputs came from and what was done to them. That is worth more to a
    reader than the openness score alone suggests.
    """
    if data_lvl == "Y" and code_lvl == "Y":
        return "Tier 1"
    if code_lvl == "Y" and data_lvl == "Partial":
        return "Tier 2"
    if data_lvl in ("Y", "Partial") and code_lvl != "Y":
        return "Tier 3"
    if code_lvl == "Y" and data_lvl == "Raw Data":
        return "Tier 4"
    if code_lvl == "Y" and data_lvl == "N":
        return "Tier 5"
    if data_lvl in ("Raw Data", "On Demand"):
        return "Tier 6"
    return "Tier 7"


def load():
    with open(SRC, encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


def derive(rows):
    out = []
    for r in rows:
        data_lvl = r["Data Publicly Available? (Y/N/Partial)"].strip()
        code_lvl = r["Replication Code? (Y/N/Partial)"].strip()
        ds = DATA_SCORE[data_lvl]
        cs = CODE_SCORE[code_lvl]
        openness = round((ds + cs) / 2, 4)

        flags = [f for f in TOPIC_FLAGS if _flag(r[f])]
        clusters = sorted(
            name for name, cols in CLUSTERS.items() if any(_flag(r[c]) for c in cols)
        )
        methods = []
        for c in ("Method (primary)", "Method (secondary)"):
            m = r[c].strip()
            if m and m not in methods:
                methods.append(m)
        sources = []
        for c in ("Data Source (primary)", "Data Source (secondary)"):
            s = r[c].strip()
            if s and s not in sources:
                sources.append(s)

        start, end, pub = (
            _year(r["Dataset Start Year"], min),
            _year(r["Dataset End Year"], max),
            _year(r["Publication Year"], max),
        )
        coverage = f"{start}–{end}" if start and end else (str(end) if end else "")
        window = (end - start + 1) if (start and end) else None
        lag = (pub - end) if (pub and end) else None

        out.append(
            {
                "paper_id": r["PAPER ID"].strip(),
                "journal": r["Journal"].strip(),
                "citation": r["Full Citation (Author, Year, Journal)"].strip(),
                "short_title": r["Short Title/ Keyword"].strip(),
                "data_description": r["Description of data"].strip(),
                "paper_link": r["Direct link"].strip(),
                "publication_year": pub,
                "topic_flags": flags,
                "topic_codes": [TOPIC_CODE[f] for f in flags],
                "clusters": clusters,
                "method_primary": r["Method (primary)"].strip(),
                "method_secondary": r["Method (secondary)"].strip(),
                "method_codes": [METHOD_CODE.get(m, "OTH") for m in methods],
                "source_primary": r["Data Source (primary)"].strip(),
                "source_secondary": r["Data Source (secondary)"].strip(),
                "source_codes": [SOURCE_CODE.get(x, "OTH") for x in sources],
                "licensing_exposure": licensing_exposure(r),
                "licensing_code": LICENSING_CODE[licensing_exposure(r)],
                "dataset_start_year": start,
                "dataset_end_year": end,
                "coverage": coverage,
                "coverage_window_years": window,
                "lag_years": lag,
                "geographic_scope": r["Data Geographic Scope"].strip(),
                "geographic_notes": r["Geographic Notes"].strip(),
                "unit_of_observation": r["Unit of Observation"].strip(),
                "data_availability": data_lvl,
                "data_score": ds,
                "data_link": r["Data Access Link / Repository"].strip(),
                "code_availability": code_lvl,
                "code_score": cs,
                "code_link": r["Code Access Link / Repository"].strip(),
                "openness_score": openness,
                "openness_band": openness_band(openness, data_lvl, code_lvl),
                "curation_tier": curation_tier(data_lvl, code_lvl),
                "could_be_open": r["Could be open-source (Y/N/Partial)"].strip(),
            }
        )
    return out


def write(recs):
    cols = list(recs[0].keys())
    csv_path = os.path.join(ROOT, "data", "sustfin_datasets.csv")
    with open(csv_path, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for rec in recs:
            flat = {
                k: ("; ".join(v) if isinstance(v, list) else ("" if v is None else v))
                for k, v in rec.items()
            }
            w.writerow(flat)
    json_path = os.path.join(ROOT, "data", "sustfin_datasets.json")
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(recs, fh, indent=2, ensure_ascii=False)
    return csv_path, json_path


if __name__ == "__main__":
    recs = derive(load())
    assert len(recs) == 109, f"expected 109 rows, got {len(recs)}"
    assert len({r["paper_id"] for r in recs}) == 109, "duplicate paper ids"
    for p in write(recs):
        print("wrote", os.path.relpath(p, ROOT))
